// const { WebClient } = require('@slack/web-api');

// const options = {};
// const web = new WebClient(process.env.SLACK_TOKEN, options);

// const sendSlackMessage = async (message, channel = null) => {
//     return new Promise(async (resolve, reject) => {
//         const channelId = channel || process.env.SLACK_CHANNEL_ID;
//         try {
//             const resp = await web.chat.postMessage({
//                 blocks: message,
//                 channel: channelId,
//             });
//             return resolve(true);
//         } catch (error) {
//             console.log('ERROR: Failed to send message!', error)
//             return resolve(true);
//         }
//     });
// };


// console.log('🚀 Slack Notifier 🚀');

// const sendMessage = async(message) => {
//     await sendSlackMessage(message);
// }

// sendMessage('This is generated by Notifier Test App')

// // const fetch = require('node-fetch');
// import fetch from 'node-fetch';

// // const url = 'https://hooks.slack.com/services/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';
// const url = process.env.SLACK_WEBHOOK_URL;
// const data = {
//   text: 'Hello, World!'
// };

// fetch(url, {
//   method: 'POST',
//   headers: {
//     'Content-type': 'application/json'
//   },
//   body: JSON.stringify(data)
// })
//   .then(response => response.json())
//   .then(result => {
//     console.log(result);
//   })
//   .catch(error => {
//     console.error('Error:', error);
//   });


const axios = require('axios');

const url = process.env.SLACK_WEBHOOK_URL;
const data = {
  text: 'Hello, World!'
};

axios.post(url, data)
  .then(response => {
    console.log(response.data);
  })
  .catch(error => {
    console.error('Error:', error);
  });
